"""20251208_204229_initial schema with template_name

Revision ID: f1dae44bf607
Revises: 
Create Date: 2025-12-08 20:42:30.087377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1dae44bf607'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('template_name', sa.String(length=100), nullable=True))
    op.alter_column('users', 'preferred_currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False,
               existing_server_default=sa.text("'NGN'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'preferred_currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True,
               existing_server_default=sa.text("'NGN'::character varying"))
    op.drop_column('invoices', 'template_name')
    # ### end Alembic commands ###
